### ISSUE TITLE
RubyNLP

### ISSUE THREAD

**Issue by arbox** [famished-tiger/Rley#1]
Dear @famished-tiger,

I've recently added your project to our RubyNLP list: https://github.com/arbox/nlp-with-ruby

I wonder if you want to participate in the Ruby for NLP network. You could do this in a very simple step by adding the `rubynlp` topic to your GitHub repository. You may want to spread a word on Twitter or on other media :)

Thank you for the project!

**Comment by famished-tiger** [comment]
Hello @arbox,
Many thanks for inserting Rley project in your **Awesome NLP with Ruby** resource list. That's great.
For a nice win-win, I added the `rubynlp` topic and also a link to the resource list directly in the `README.md` file.

Cheers!

**Comment by arbox** [comment]
Let's build the RubyNLP network together :) Thank you!
